### ISSUE TITLE
make.header()

### ISSUE THREAD

**Issue by Boxedpig** [WenjianBI/SPAGE#1]
Hi, Dr Bi,
I think make.header could not work when the number of Envv.mtx's columns is larger than 1. Maybe the later cycle will cover the former.
![image](https://user-images.githubusercontent.com/37393184/78462177-a77ab000-769d-11ea-9b38-87ec5e7c91c0.png)
Looking forward to your reply.
Thanks.

**Comment by WenjianBI** [comment]
Thank you for pointing it out. I just revised it. Please check the following commit. 
https://github.com/WenjianBI/SPAGE/commit/f450c2da0095d975e294eabbc4581f2dcc100096

I did not set the notification so I missed the issue. Sorry for the late reply. Please let me know if the issue has been resolved.
